name: Upgrade cluster node images

on:
  schedule:
    - cron: '0 3 */15 * *'
  workflow_dispatch:
  
jobs:
  upgrade-node:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.7
      with:
        inlineScript: az aks upgrade -g {resourceGroupName} -n {aksClusterName} --node-image-only --yes
